apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile-deployment
  namespace: api
  labels:
    app: userprofile-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
      - name: userprofile
        image: openhackacr.azurecr.io/tripinsights/userprofile:1.0
        volumeMounts:
        - name: config-vol
          mountPath: /secrets
        env:
        - name: SQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: oh-config-map-api
              key: SQL_PASSWORD
        - name: SQL_SERVER
          valueFrom:
            configMapKeyRef:
              name: oh-config-map-api
              key: SQL_SERVER
        ports:
        - containerPort: 80
      volumes:
      - name: config-vol
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: oh-secrets
          nodePublishSecretRef:                       # Only required when using service principal mode
            name: secrets-store-creds
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile-service
spec:
  type: ClusterIP
  selector:
   app: userprofile
  ports:
    - targetPort: 80
      port: 80
