apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer-deployment
  namespace: web
  labels:
    app: tripviewer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - name: tripviewer
        image: openhackacr.azurecr.io/tripinsights/tripviewer:1.0
        env:
        - name: USERPROFILE_API_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: oh-config-map-web
              key: USERPROFILE_API_ENDPOINT
        - name: TRIPS_API_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: oh-config-map-web
              key: TRIPS_API_ENDPOINT
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer-service
spec:
  type: ClusterIP
  selector:
   app: tripviewer
  ports:
    - targetPort: 80
      port: 80
