apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: oh-secrets 
  namespace: api
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    keyvaultName: secret-store-0Nv7eBAlhb 
    objects: |
      array:
        - |
          objectName: SQL-PASSWORD              
          objectType: secret
          objectVersion: ""
          objectAlias: SQL_PASSWORD
        - |
          objectName: SQL-SERVER
          objectType: secret
          objectVersion: ""
          objectAlias: SQL_SERVER
        - |
          objectName: SQL-USER
          objectType: secret
          objectVersion: ""
          objectAlias: SQL_USER
        - |
          objectName: SQL-DBNAME
          objectType: secret
          objectVersion: ""
          objectAlias: SQL_DBNAME
    tenantId: b99225e4-6d6d-446d-a537-62d4fb7f1055 
